@host = http://localhost:3001/url

#GET https://api.m3o.com/v1/weather/Forecast
 #https://jsonmock.hackerrank.com/api/moviesdata/search/?Title=spiderman
POST {{host}}/register
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImEuYWRlbEBlZ3lwdHNtYXJ0Y2FyZHMuY29tIiwiX2lkIjoiNjIxMjNjYThmZDg2NDkzNjJkNTgwNWY4IiwiaWF0IjoxNjQ1MzYyNDAyfQ.sGNdV0JUhqHAxnXtlry5SG8N2M4TonFEBrU-zCZknKQ

{
    "name"  : "adelAPP",
    "type"  : "GET",
    "url"   : "api.m3o.com",
    "protocol":"HTTPS",
    "path":  "/v1/weather/Forecast",
    "interval":1,
    "webhooks":{ "discord":"https://discord.com/api/webhooks/944244417391386677/gPUINLI_mdmQPi3LlHzSwks8jaHCd_dd_2IM6HNQ_EEyK6FHDCPg9taZadJoaSbaFsEy"}
}

###
GET https://reqres.in/api/users?page=2

###
GET https://jsonmock.hackerrank.com/api/moviesdata/search/?Title=spiderman


###
GET {{host}}/getChecker/myApp

###
GET https://reqres.in/users?page=1

###
GET https://api.m3o.com/v1/weather/Forecast