@host = http://localhost:3001

POST {{host}}/auth/login
Content-Type: application/json

{
    "email":"a.soliman@gmail232.com",
    "password":"123123123"
}

###

POST {{host}}/auth/signup
Content-Type: application/json

{
    "name"  :"Abdelrahman S12olim3an",
    "email" :"a.soliman@gmail23222.com",
    "mobile":"02113328871",
    "password":"123123123",
    "testNewProp":"test"
}

###
GET {{host}}/auth/test
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImEuc29saW1hbkBnbWFpbDIzMi5jb20iLCJfaWQiOiI2MWZlY2Y5MGE3MDhlYzY0Yzk2ZTIwYzQiLCJpYXQiOjE2NDQyMDE0OTF9.HdiJkS0KVUDJovAYgSr3t8xAEKV_8ULe1FZf50mFha0



###
GET https://jsonmock.hackerrank.com/api/moviesdata/search/?Title=spiderman
